---
title: "OR IJGIS FAIR Evaluation Data Cleaning Script"

output: html_notebook

#Date: Spring 2025

#Credit to: Zijun Li, Peter Kedron
---

#
# Load data, Read the CSV---------------------------------
#

data <- read.csv("workingdirectory/Computational Reproducibilty Screener_May 22, 2025_12.05.csv")

#
# Remove unwanted columns by column names-----------------
#

data <- data[, !(names(data) %in% c("StartDate", "EndDate","Status","Finished","IPAddress","RecordedDate","RecipientFirstName","RecipientLastName","RecipientEmail","ExternalReference","LocationLatitude","LocationLongitude","DistributionChannel","UserLanguage","First","Last"))]

#
# Save new CSV as Cleaned Data-----------------------------
#

write.csv(data, "workingdirectory/RawFromQuatrix_cleaned.csv", row.names = FALSE)

#
# Rename specific columns----------------------------------
#

names(data)[names(data) == "Progress"] <- "progress"
names(data)[names(data) == "Duration..in.seconds."] <- "duration"
names(data)[names(data) == "ResponseId"] <- "qualtrics_id"
names(data)[names(data) == "ID."] <- "id"
names(data)[names(data) == "DOI"] <- "doi"
names(data)[names(data) == "Data.Filter."] <- "d_filter"
names(data)[names(data) == "Synth.data."] <- "d_synth"
names(data)[names(data) == "Code.Filter."] <- "c_filter"
names(data)[names(data) == "Q30"] <- "comments"
names(data)[names(data) == "SCR.1"] <- "cr-1"
names(data)[names(data) == "SCR.1.1."] <- "cr-1-1	"
names(data)[names(data) == "SCR.1.2"] <- "cr-1-2"
names(data)[names(data) == "SCR.3"] <- "cr-3"
names(data)[names(data) == "SCR.3_5_TEXT"] <- "cr-3-text"
names(data)[names(data) == "SCR.4"] <- "cr-4"
names(data)[names(data) == "SCR.4_3_TEXT"] <- "cr-4-text"
names(data)[names(data) == "DCR.1._1"] <- "cr-f-1"
names(data)[names(data) == "DCR.1._2"] <- "cr-f-2"
names(data)[names(data) == "DCR.1.1"] <- "cr-f-1-1"
names(data)[names(data) == "DCR.2_1"] <- "cr-a-1"
names(data)[names(data) == "DCR.2_2"] <- "cr-a-2"
names(data)[names(data) == "DCR.3_1"] <- "cr-i-1"
names(data)[names(data) == "DCR.3_2"] <- "cr-i-2"
#Are the available code used in the publication Interoperable? - Publication or code specifies computing infrastructure used
names(data)[names(data) == "DCR.3_4"] <- "cr-i-3"
names(data)[names(data) == "DCR.4_1"] <- "cr-r-1"
names(data)[names(data) == "DCR.4_2"] <- "cr-r-2"
names(data)[names(data) == "DCR.4_3"] <- "cr-r-3"
names(data)[names(data) == "DCR.4.1"] <- "cr-r-1-1"
names(data)[names(data) == "SDR.1"] <- "dr-1"
names(data)[names(data) == "SDR.1.1"] <- "dr-1-1"
names(data)[names(data) == "SDR.1.2"] <- "dr-1-2"
names(data)[names(data) == "SDR.1.2_5_TEXT"] <- "dr-1-2-1"
#Is a metadata provided for the data?
names(data)[names(data) == "SDR.2.1"] <- "dr-2"
names(data)[names(data) == "FDR.1_1"] <- "dr-f-1"
names(data)[names(data) == "FDR.1_2"] <- "dr-f-2"
names(data)[names(data) == "FDR.1_3"] <- "dr-f-3"
names(data)[names(data) == "FDR.1.1"] <- "dr-f-1-1"
names(data)[names(data) == "FDR.2_1"] <- "dr-a-1"
names(data)[names(data) == "FDR.2_2"] <- "dr-a-2"
names(data)[names(data) == "FDR.3_1"] <- "dr-i-1"
names(data)[names(data) == "FDR.3_2"] <- "dr-i-2"
names(data)[names(data) == "FDR.4_1"] <- "dr-r-1"
names(data)[names(data) == "FDR.4_2"] <- "dr-r-2"
names(data)[names(data) == "FDR.4_3"] <- "dr-r-3"
names(data)[names(data) == "FDR.4.1."] <- "dr-r-1-1"

#
# Save new CSV as Renamed Data-----------------------------
#

write.csv(data, "workingdirectory/RawFromQuatrix_cleaned_Renamed.csv", row.names = FALSE)

#
# Modify the cell------------------------------------------
#

data[34, "id"] <- 22

#
# Keep only rows where 'id' is not NA and not an empty string------------------------------------------
#

data_clean <- data[!(is.na(data$id) | data$id == ""), ]

#
# Save new CSV as modify id Data------------------------------------------
#

write.csv(data_clean, "workingdirectory/RawFromQuatrix_cleaned_Renamed_modify_id.csv", row.names = FALSE)






